version: "3"
services:
  nginx:
    container_name: web-nginx
    image: nginx:latest
    restart: always
    ports:
      - 9080:80
      - 9443:443
    volumes:
      - D:/docker/tree/frontend:/home/webserver
      - D:/docker/tree/nginx/nginx.conf:/etc/nginx/nginx.conf
      - D:/docker/tree/nginx/conf.d:/etc/nginx/conf.d

  db_mysql:
    container_name: db-mysql
    image: mysql:8.0.15
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-authentication-plugin=mysql_native_password
    volumes:
      - D:/docker/tree/mysql/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
#    expose:
#      - 3306

  db_redis:
    container_name: db-redis
    image: redis:latest
    ports:
      - 6379:6379
#    expose:
#      - 6379

  webserver:
    restart: always
    container_name: web-node-backend
    image: node:10.15.3-alpine
#    image: anjia0532/distroless.nodejs:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        build_no: 1
    ports:
      - 3000:3000
#    volumes:
#      - D:/docker/tree/backend:/home/app
#    env_file: .env
#    environment:
#      - APP=bin/www
#      - PM2PARAM=-i 0
#      # Redis config
#      - PROJECT_NAME=WEBPROXY
#      - REDIS_PWD=123456
#      - REDIS_POOL_SIZE=100
#      - REDIS_INDEX=1
#      - REDIS_HOST=db_redis:6379
    depends_on:
      - db_mysql
      - db_redis
    links:
      - db_redis
      - db_mysql
